apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: cinema-service
  template:
    metadata:
      labels:
        app: cinema-service
    spec:
      containers:
        - name: cinema-service
          env:
            - name: POSTGRES_HOST
              value: postgres
          image: ghcr.io/darthkali/microkino:cinemaservice
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com