apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          env:
            - name: POSTGRES_USER
              value: microkino
            - name: POSTGRES_PASSWORD
              value: m1cr0k1n0
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: testdb
          ports:
            - containerPort: 5432
              name: postgres
  selector:
    matchLabels:
      app: postgres