apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-service
  namespace: default
  labels:
    app: show-service
spec:
  selector:
    matchLabels:
      app: show-service
  template:
    metadata:
      labels:
        app: show-service
    spec:
      containers:
        - name: show-service
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: KAFKA_SERVER
              value: kafka-service:9092
          image: ghcr.io/fh-erfurt/microkino:showservice
          imagePullPolicy: Always
#          ports:
#            - name: web
#              containerPort: 8090
      imagePullSecrets:
        - name: dockerconfigjson-github-com