apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: default
  labels:
    app: movie-service
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: KAFKA_SERVER
              value: kafka-service:9092
          image: ghcr.io/fh-erfurt/microkino:movieservice
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com