apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinemaservice
  labels:
    app: cinemaservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cinemaservice
  template:
    metadata:
      labels:
        app: cinemaservice
    spec:
      containers:
        - name: cinemaservice
          image: ghcr.io/darthkali/microkino:cinemaservice
          ports:
            - containerPort: 8080

