apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  rules:
    - host: traefik-ui.penis
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: traefik-web-ui
                port:
                  name: web