#https://robertbrem.github.io/Microservices_with_Kubernetes/19_CQRS_with_Kafka/01_Setup_Kafka/
#https://blog.datumo.io/setting-up-kafka-on-kubernetes-an-easy-way-26ae150b9ca8
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-kafka:7.5.3
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper-service:2181'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://:29092,PLAINTEXT_INTERNAL://kafka-service:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"



            #            - name: KAFKA_ADVERTISED_HOST_NAME
            #              value: kafka-deployment
            #            - name: KAFKA_LISTENERS
            #              value: PLAINTEXT://:9092
            #            - name: KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS
            #              value: "60000"
            #            - name: ENABLE_AUTO_EXTEND
            #              value: "true"
            #            - name: KAFKA_RESERVED_BROKER_MAX_ID
            #              value: "999999999"
            #            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            #              value: "true"
            #            - name: KAFKA_PORT
            #              value: "9092"
            #            - name: KAFKA_ADVERTISED_PORT
            #              value: "9092"
            #            - name: KAFKA_ADVERTISED_HOST_NAME
            #              value: "localhost"
            #            - name: KAFKA_ZOOKEEPER_CONNECT
            #              value: zookeeper-service:2181
            #            - name: KAFKA_LISTENERS
            #              value: PLAINTEXT://:9092
            #            - name: KAFKA_ADVERTISED_LISTENERS
            #              value: PLAINTEXT://kafka-service:9092
            #            - name: KAFKA_ADVERTISED_PORT
            #              value: "9092"
            #            - name: KAFKA_ADVERTISED_HOST_NAME
            #              value: localhost
            #            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            #              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT



