apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
#  labels:
#    name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
    - port: 2181
      protocol: TCP
      targetPort: 2181
#    - name: client
#    - name: follower
#      port: 2888
#      protocol: TCP
#    - name: leader
#      port: 3888
#      protocol: TCP
