apiVersion: v1
kind: Service
metadata:
  name: cinemaservice
spec:
  type: NodePort
  selector:
    app: cinemaservice
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
