apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: cinema-service
  template:
    metadata:
      labels:
        app: cinema-service
    spec:
      containers:
        - name: cinema-service
          env:
            - name: POSTGRES_HOST
              value: postgres
          image: ghcr.io/fh-erfurt/microkino:cinemaservice
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com

#---
#kind: Deployment
#apiVersion: apps/v1
#metadata:
#  namespace: default
#  name: whoami
#  labels:
#    app: whoami
#
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: whoami
#  template:
#    metadata:
#      labels:
#        app: whoami
#    spec:
#      containers:
#        - name: whoami
#          image: traefik/whoami
#          ports:
#            - name: web
#              containerPort: 80